[project]
name = "clarity-market"
requirements = []

[contracts.appmap]
path = "contracts/appmap.clar"
depends_on = []

[contracts.nft-approvable-trait]
path = "contracts/nft-approvable-trait.clar"
depends_on = []

[contracts.nft-trait]
path = "contracts/nft-trait.clar"
depends_on = []

[contracts.loopbomb]
path = "contracts/loopbomb.clar"
depends_on=["nft-approvable-trait", "nft-trait"]